### ISSUE TITLE
jsone is not an application that needs starting

### ISSUE THREAD

**Issue by dialtone** [asabil/raven-erlang#20]
Not sure you should put jsone in the app.src file under applications.

**Comment by asabil** [comment]
Actually you need to for it to be picked up by the release generation tool (systool, reltool, relx...).

The applications field lists the dependencies whether they need starting or not.

**Comment by dialtone** [comment]
Yeah that's one of the side effects of that field but you can't use it for libraries anyway. This is the documentation: http://erlang.org/doc/man/app.html

```
applications
All applications that must be started before this application is allowed to be started. systools uses this list to generate correct start scripts. Defaults to the empty list, but notice that all applications have dependencies to (at least) Kernel and STDLIB.
```

`jsone` is not an application that must be started and if you leave it there it's going to fail boot because it can't be started. And this is the result of launching it:

```
ERL_LIBS=_build/default/lib erl -s crypto -s inets -s ssl                                                                                                                                  
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V8.3  (abort with ^G)
1> application:start(raven).
{error,{not_started,jsone}}
```

**Comment by asabil** [comment]
You are supposed to use:
`application:ensure_all_started/1`
